name: React TypeScript CI/CD with SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2244
        script: |
          ls -l
          pwd
          # cd /path/to/your/react/app
          # sudo pm2 stop all
          # sudo rm -rf *
          # sudo cp -r /path/to/your/react/app/build/* .
          # sudo pm2 start ecosystem.config.js --env production
