name: React TypeScript CI/CD with SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.1'  #Specify the Node.js version you want to use


    - name: Set up environment variables
      run: |
        echo "CI=false" >> $GITHUB_ENV
        echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" >> $GITHUB_ENV
        ls -l && pwd

    - name: Install dependencies and build
      run: |
        npm install
        npm install thirdweb --legacy-peer-deps
        npm run build


    - name: Zip & Rsync
      run: |
        ls -l && pwd
        # Wait for ongoing changes to finish (optional)
        sleep 5
        #zip -r code.zip --exclude=*.git --exclude=node_modules ./*
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem  # Store private key in key.pem
        chmod 400 key.pem
        ls -l
        rsync -avzrp -e "ssh -p 2244 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i key.pem" * ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/ubuntu/2024-Heale-Desktop/

    - name: Deploy Frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2244
        script: |
          ls -l && pwd
          cd /home/ubuntu/2024-Heale-Desktop/
          pm2 start "npm run start"
          pm2 restart 0
          # npm install 
